D405:
  head_base_to_cam: [0.102, 0.009, 0.044, -90.0, 0.0, -90.0] # 42*42*23
  mount_to_cam: [0.047, 0.009, 0.057, -90.0, 0.0, -90.0]
  camera_mount_link: link_head_2
  temp_supported: false

D435:
  head_base_to_cam: [0.1045, -0.0115, 0.044, -90.0, 0.0, -90.0]
  mount_to_cam: [0.0495, 0.0325, 0.057, -90.0, 0.0, -90.0]
  camera_mount_link: link_head_2
  temp_supported: false

D435I:
  head_base_to_cam: [0.1045, -0.0115, 0.044, -90.0, 0.0, -90.0]
  mount_to_cam: [0.0495, 0.0325, 0.057, -90.0, 0.0, -90.0]
  camera_mount_link: link_head_2
  temp_supported: false

D455: # no data
  head_base_to_cam: [0.0, 0.0, 0.0, -90.0, 0.0, -90.0] # you don't need to change [-90.0,0.0,-90.0]
  mount_to_cam: [0.0, 0.0, 0.0, -90.0, 0.0, -90.0]
  camera_mount_link: link_head_2
  temp_supported: false

D415: # no data
  head_base_to_cam: [0.0, 0.0, 0.0, -90.0, 0.0, -90.0]
  mount_to_cam: [0.0, 0.0, 0.0, -90.0, 0.0, -90.0]
  camera_mount_link: link_head_2
  temp_supported: false
  

